version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - sample_dj_db:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - '5433:5432'

volumes:
  sample_dj_db: