# Generated by Django 4.1.5 on 2023-02-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0002_sometable"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pid", models.CharField(max_length=250)),
                ("step_num", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("finished", "Finished"), ("waiting", "Waiting")],
                        max_length=250,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("pid", "step_num"), name="lesson_unique"
            ),
        ),
    ]
