# Generated by Django 4.1.5 on 2023-02-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0004_project_project_status_check"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("address", models.CharField(max_length=250, null=True)),
            ],
        ),
    ]
