# Generated by Django 4.1.5 on 2023-02-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0005_person"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeqTbl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seq", models.IntegerField()),
                ("name", models.CharField(max_length=250)),
            ],
        ),
    ]
