# Generated by Django 4.1.5 on 2023-02-02 06:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0006_seqtbl"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Person",
        ),
        migrations.DeleteModel(
            name="PrefPopulation",
        ),
        migrations.DeleteModel(
            name="Project",
        ),
        migrations.DeleteModel(
            name="SeqTbl",
        ),
        migrations.DeleteModel(
            name="SomeTable",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
