# Generated by Django 4.1.5 on 2023-02-02 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0008_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=100)),
                ("submitted_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
