# Generated by Django 4.1.5 on 2023-02-03 08:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0011_item_created_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Shop",
        ),
    ]
