# Generated by Django 4.1.5 on 2023-02-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0012_delete_shop"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("item", models.CharField(max_length=250)),
            ],
        ),
    ]
