# Generated by Django 4.1.5 on 2023-02-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0013_shop"),
    ]

    operations = [
        migrations.CreateModel(
            name="prc_amt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prc_date", models.DateTimeField()),
                ("amount", models.IntegerField()),
            ],
        ),
    ]
