# Generated by Django 4.1.5 on 2023-02-03 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0014_prc_amt"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="prc_amt",
            new_name="Prc",
        ),
    ]
