# Generated by Django 4.1.5 on 2023-02-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sample", "0015_rename_prc_amt_prc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cust_id", models.CharField(max_length=10)),
            ],
        ),
    ]
